### ISSUE TITLE
Issue-updated redis config

### ISSUE THREAD

**Issue by satomichru** [satomichru/nexusai#12]
Automated Review Comments
Issues in packages/api/pages/api/config/redis.js:
  - (2, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
Issues in plan.md:
  - (4, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
