### ISSUE TITLE
Issue-first commit

### ISSUE THREAD

**Issue by satomichru** [satomichru/nexusai#2]
Automated Review Comments
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
Issues in packages/api/README.md:
  - (4, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
Issues in packages/api/jsconfig.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in packages/api/next.config.js:
  - (2, 'Hardcoded string found')
Issues in packages/api/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in packages/api/pages/_document.js:
  - (6, 'Hardcoded string found')
Issues in packages/api/pages/api/config/env.js:
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in packages/api/pages/api/config/mongodb.js:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in packages/api/pages/api/controller/user.js:
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in packages/api/pages/api/hello.js:
  - (5, 'Hardcoded string found')
Issues in packages/api/pages/api/middlewares/error.js:
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in packages/api/pages/index.js:
  - (7, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (84, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
Issues in packages/api/public/next.svg:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in packages/api/public/vercel.svg:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in packages/api/styles/globals.css:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
