### ISSUE TITLE
Issue-rename api -> app

### ISSUE THREAD

**Issue by satomichru** [satomichru/nexusai#20]
Automated Review Comments
Issues in packages/api/nodemon.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in packages/api/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
Issues in packages/api/src/app.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
Issues in packages/api/src/config/env.ts:
  - (3, 'Hardcoded string found')
Issues in packages/api/src/config/logger.ts:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in packages/api/src/config/prisma.ts:
  - (12, 'Hardcoded string found')
Issues in packages/api/src/config/redis.ts:
  - (2, 'Hardcoded string found')
Issues in packages/api/src/controller/user.controller.ts:
  - (2, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
Issues in packages/api/src/lib/error.ts:
  - (5, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in packages/api/src/lib/exception.ts:
  - (9, 'Hardcoded string found')
Issues in packages/api/src/lib/jwt.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in packages/api/src/lib/schema_validation.ts:
  - (2, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
Issues in packages/api/src/lib/sendResponse.ts:
  - (2, 'Hardcoded string found')
Issues in packages/api/src/lib/zodValidation.ts:
  - (3, 'Hardcoded string found')
Issues in packages/api/src/middlewares/auth.ts:
  - (2, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
Issues in packages/api/src/middlewares/error.ts:
  - (2, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in packages/api/src/middlewares/logger.ts:
  - (3, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in packages/api/src/middlewares/subscription.ts:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in packages/api/src/prisma/schema.prisma:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (85, 'Line exceeds 80 characters')
  - (88, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
Issues in packages/api/src/routes/auth.route.ts:
  - (2, 'Hardcoded string found')
Issues in packages/api/src/routes/og.route.tsx:
  - (2, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
Issues in packages/api/src/routes/subscription.route.ts:
  - (2, 'Hardcoded string found')
Issues in packages/api/src/routes/user.route.ts:
  - (2, 'Hardcoded string found')
Issues in packages/api/src/routes/webhook.route.ts:
  - (2, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
