### ISSUE TITLE
Issue-added major changes

### ISSUE THREAD

**Issue by satomichru** [satomichru/nexusai#23]
Automated Review Comments
Issues in packages/app/components/Topbar.jsx:
  - (2, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in packages/app/config/env.js:
  - (4, 'Hardcoded string found')
Issues in packages/app/config/font.js:
  - (3, 'Hardcoded string found')
Issues in packages/app/pages/[url_id].jsx:
  - (6, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (85, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (115, 'Line exceeds 80 characters')
  - (122, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
Issues in packages/app/pages/api/service/nocred.js:
  - (22, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
Issues in packages/app/pages/index.jsx:
  - (10, 'Line exceeds 80 characters')
Issues in packages/app/tailwind.config.cjs:
  - (2, 'Hardcoded string found')
Issues in packages/extension/background.js:
  - (26, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
Issues in packages/extension/index.html:
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (88, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
Issues in packages/extension/manifest.json:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in packages/extension/popup.js:
  - (29, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
