### ISSUE TITLE
Issue-added markdown assets

### ISSUE THREAD

**Issue by satomichru** [satomichru/nexusai#25]
Automated Review Comments
Issues in packages/api/nodemon.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in packages/api/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in packages/api/src/config/env.ts:
  - (3, 'Hardcoded string found')
Issues in packages/api/src/controller/user.controller.ts:
  - (2, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
Issues in packages/api/src/lib/google.auth.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
Issues in packages/api/src/prisma/schema.prisma:
  - (71, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
Issues in packages/api/src/routes/auth.route.ts:
  - (20, 'Line exceeds 80 characters')
Issues in packages/api/src/services/auth.service.ts:
  - (2, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (197, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
