### ISSUE TITLE
Issue-added some seo tags

### ISSUE THREAD

**Issue by satomichru** [satomichru/nexusai#31]
Automated Review Comments
Issues in packages/app/pages/_document.jsx:
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
