### ISSUE TITLE
Issue-added major changes

### ISSUE THREAD

**Issue by satomichru** [satomichru/nexusai#35]
Automated Review Comments
Issues in packages/app/pages/[url_id].jsx:
  - (17, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
Issues in packages/app/pages/_app.jsx:
  - (14, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
Issues in packages/app/pages/_document.jsx:
  - (4, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
Issues in packages/extension/background.js:
  - (48, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (88, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
Issues in packages/extension/manifest.json:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in packages/extension/popup.js:
  - (20, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
