### ISSUE TITLE
Issue-updated extention and app

### ISSUE THREAD

**Issue by satomichru** [satomichru/nexusai#37]
Automated Review Comments
Issues in packages/extension/background.js:
  - (25, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
Issues in packages/extension/content.js:
  - (18, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
