### ISSUE TITLE
Issue-updated app

### ISSUE THREAD

**Issue by satomichru** [satomichru/nexusai#39]
Automated Review Comments
Issues in packages/app/components/Topbar.jsx:
  - (3, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
Issues in packages/app/pages/[url_id].jsx:
  - (10, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
Issues in packages/app/pages/index.jsx:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
