### ISSUE TITLE
Issue-updated app

### ISSUE THREAD

**Issue by satomichru** [satomichru/nexusai#41]
Automated Review Comments
Issues in packages/api/src/middlewares/auth.ts:
  - (2, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
Issues in packages/api/src/routes/user.route.ts:
  - (1, 'Hardcoded string found')
Issues in packages/api/src/services/auth.service.ts:
  - (2, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
Issues in packages/app/pages/index.jsx:
  - (2, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
