### ISSUE TITLE
Issue-started api dev

### ISSUE THREAD

**Issue by satomichru** [satomichru/nexusai#6]
Automated Review Comments
Issues in packages/api/config/font.js:
  - (5, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in packages/api/package.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in packages/api/pages/[credId].jsx:
  - (2, 'Hardcoded string found')
Issues in packages/api/pages/_document.jsx:
  - (6, 'Hardcoded string found')
Issues in packages/api/pages/api/config/env.js:
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in packages/api/pages/api/config/mongodb.js:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
Issues in packages/api/pages/api/config/redis.js:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in packages/api/pages/api/url/create.js:
  - (9, 'Hardcoded string found')
Issues in packages/api/styles/globals.css:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (61, 'Line exceeds 80 characters')
Issues in packages/api/tailwind.config.js:
  - (2, 'Hardcoded string found')
Issues in packages/extension/manifest.json:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in packages/extension/popup.js:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in yarn.lock:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
  - (84, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (98, 'Line exceeds 80 characters')
  - (99, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (125, 'Line exceeds 80 characters')
  - (126, 'Line exceeds 80 characters')
  - (130, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (139, 'Line exceeds 80 characters')
  - (143, 'Line exceeds 80 characters')
  - (144, 'Line exceeds 80 characters')
  - (155, 'Line exceeds 80 characters')
  - (156, 'Line exceeds 80 characters')
  - (160, 'Line exceeds 80 characters')
  - (161, 'Line exceeds 80 characters')
  - (165, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (173, 'Line exceeds 80 characters')
  - (174, 'Line exceeds 80 characters')
  - (180, 'Line exceeds 80 characters')
  - (181, 'Line exceeds 80 characters')
  - (190, 'Line exceeds 80 characters')
  - (198, 'Line exceeds 80 characters')
  - (199, 'Line exceeds 80 characters')
  - (201, 'Line exceeds 80 characters')
  - (203, 'Line exceeds 80 characters')
  - (204, 'Line exceeds 80 characters')
  - (208, 'Line exceeds 80 characters')
  - (209, 'Line exceeds 80 characters')
  - (223, 'Line exceeds 80 characters')
  - (224, 'Line exceeds 80 characters')
  - (228, 'Line exceeds 80 characters')
  - (229, 'Line exceeds 80 characters')
  - (233, 'Line exceeds 80 characters')
  - (234, 'Line exceeds 80 characters')
  - (238, 'Line exceeds 80 characters')
  - (239, 'Line exceeds 80 characters')
  - (243, 'Line exceeds 80 characters')
  - (244, 'Line exceeds 80 characters')
  - (248, 'Line exceeds 80 characters')
  - (249, 'Line exceeds 80 characters')
  - (255, 'Line exceeds 80 characters')
  - (256, 'Line exceeds 80 characters')
  - (260, 'Line exceeds 80 characters')
  - (261, 'Line exceeds 80 characters')
  - (265, 'Line exceeds 80 characters')
  - (266, 'Line exceeds 80 characters')
  - (270, 'Line exceeds 80 characters')
  - (271, 'Line exceeds 80 characters')
  - (275, 'Line exceeds 80 characters')
  - (276, 'Line exceeds 80 characters')
  - (278, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (286, 'Line exceeds 80 characters')
  - (287, 'Line exceeds 80 characters')
  - (293, 'Line exceeds 80 characters')
  - (294, 'Line exceeds 80 characters')
  - (300, 'Line exceeds 80 characters')
  - (301, 'Line exceeds 80 characters')
  - (305, 'Line exceeds 80 characters')
  - (306, 'Line exceeds 80 characters')
  - (310, 'Line exceeds 80 characters')
  - (311, 'Line exceeds 80 characters')
  - (315, 'Line exceeds 80 characters')
  - (316, 'Line exceeds 80 characters')
  - (320, 'Line exceeds 80 characters')
  - (321, 'Line exceeds 80 characters')
  - (325, 'Line exceeds 80 characters')
  - (326, 'Line exceeds 80 characters')
  - (332, 'Line exceeds 80 characters')
  - (333, 'Line exceeds 80 characters')
  - (339, 'Line exceeds 80 characters')
  - (340, 'Line exceeds 80 characters')
  - (351, 'Line exceeds 80 characters')
  - (352, 'Line exceeds 80 characters')
  - (358, 'Line exceeds 80 characters')
  - (359, 'Line exceeds 80 characters')
  - (366, 'Line exceeds 80 characters')
  - (367, 'Line exceeds 80 characters')
  - (371, 'Line exceeds 80 characters')
  - (372, 'Line exceeds 80 characters')
  - (376, 'Line exceeds 80 characters')
  - (377, 'Line exceeds 80 characters')
  - (383, 'Line exceeds 80 characters')
  - (384, 'Line exceeds 80 characters')
  - (390, 'Line exceeds 80 characters')
  - (391, 'Line exceeds 80 characters')
  - (395, 'Line exceeds 80 characters')
  - (396, 'Line exceeds 80 characters')
  - (402, 'Line exceeds 80 characters')
  - (403, 'Line exceeds 80 characters')
  - (407, 'Line exceeds 80 characters')
  - (408, 'Line exceeds 80 characters')
  - (412, 'Line exceeds 80 characters')
  - (414, 'Line exceeds 80 characters')
  - (415, 'Line exceeds 80 characters')
  - (419, 'Line exceeds 80 characters')
  - (420, 'Line exceeds 80 characters')
  - (424, 'Line exceeds 80 characters')
  - (425, 'Line exceeds 80 characters')
  - (429, 'Line exceeds 80 characters')
  - (431, 'Line exceeds 80 characters')
  - (432, 'Line exceeds 80 characters')
  - (436, 'Line exceeds 80 characters')
  - (437, 'Line exceeds 80 characters')
  - (441, 'Line exceeds 80 characters')
  - (442, 'Line exceeds 80 characters')
  - (449, 'Line exceeds 80 characters')
  - (450, 'Line exceeds 80 characters')
  - (456, 'Line exceeds 80 characters')
  - (458, 'Line exceeds 80 characters')
  - (459, 'Line exceeds 80 characters')
  - (464, 'Line exceeds 80 characters')
  - (465, 'Line exceeds 80 characters')
  - (473, 'Line exceeds 80 characters')
  - (474, 'Line exceeds 80 characters')
  - (476, 'Hardcoded string found')
  - (477, 'Hardcoded string found')
  - (481, 'Line exceeds 80 characters')
  - (482, 'Line exceeds 80 characters')
  - (486, 'Line exceeds 80 characters')
  - (487, 'Line exceeds 80 characters')
  - (491, 'Line exceeds 80 characters')
  - (492, 'Line exceeds 80 characters')
  - (496, 'Line exceeds 80 characters')
  - (497, 'Line exceeds 80 characters')
  - (501, 'Line exceeds 80 characters')
  - (502, 'Line exceeds 80 characters')
  - (506, 'Line exceeds 80 characters')
  - (507, 'Line exceeds 80 characters')
  - (513, 'Line exceeds 80 characters')
  - (514, 'Line exceeds 80 characters')
  - (518, 'Line exceeds 80 characters')
  - (519, 'Line exceeds 80 characters')
  - (523, 'Line exceeds 80 characters')
  - (524, 'Line exceeds 80 characters')
  - (528, 'Line exceeds 80 characters')
  - (529, 'Line exceeds 80 characters')
  - (533, 'Line exceeds 80 characters')
  - (534, 'Line exceeds 80 characters')
  - (538, 'Line exceeds 80 characters')
  - (539, 'Line exceeds 80 characters')
  - (543, 'Line exceeds 80 characters')
  - (544, 'Line exceeds 80 characters')
  - (552, 'Line exceeds 80 characters')
  - (553, 'Line exceeds 80 characters')
  - (559, 'Line exceeds 80 characters')
  - (560, 'Line exceeds 80 characters')
  - (567, 'Line exceeds 80 characters')
  - (568, 'Line exceeds 80 characters')
  - (574, 'Line exceeds 80 characters')
  - (575, 'Line exceeds 80 characters')
  - (582, 'Line exceeds 80 characters')
  - (583, 'Line exceeds 80 characters')
  - (587, 'Line exceeds 80 characters')
  - (594, 'Line exceeds 80 characters')
  - (595, 'Line exceeds 80 characters')
  - (603, 'Line exceeds 80 characters')
  - (604, 'Line exceeds 80 characters')
  - (608, 'Line exceeds 80 characters')
  - (609, 'Line exceeds 80 characters')
  - (613, 'Line exceeds 80 characters')
  - (620, 'Line exceeds 80 characters')
  - (621, 'Line exceeds 80 characters')
  - (627, 'Line exceeds 80 characters')
  - (628, 'Line exceeds 80 characters')
  - (634, 'Line exceeds 80 characters')
  - (635, 'Line exceeds 80 characters')
  - (637, 'Hardcoded string found')
  - (638, 'Hardcoded string found')
  - (639, 'Hardcoded string found')
  - (640, 'Hardcoded string found')
  - (641, 'Hardcoded string found')
  - (642, 'Hardcoded string found')
  - (646, 'Line exceeds 80 characters')
  - (647, 'Line exceeds 80 characters')
  - (655, 'Line exceeds 80 characters')
  - (656, 'Line exceeds 80 characters')
  - (660, 'Line exceeds 80 characters')
  - (661, 'Line exceeds 80 characters')
  - (667, 'Line exceeds 80 characters')
  - (674, 'Line exceeds 80 characters')
  - (675, 'Line exceeds 80 characters')
  - (677, 'Hardcoded string found')
  - (687, 'Line exceeds 80 characters')
  - (688, 'Line exceeds 80 characters')
  - (692, 'Line exceeds 80 characters')
  - (693, 'Line exceeds 80 characters')
  - (695, 'Hardcoded string found')
  - (720, 'Line exceeds 80 characters')
  - (721, 'Line exceeds 80 characters')
  - (727, 'Line exceeds 80 characters')
  - (728, 'Line exceeds 80 characters')
  - (734, 'Line exceeds 80 characters')
  - (735, 'Line exceeds 80 characters')
  - (741, 'Line exceeds 80 characters')
  - (742, 'Line exceeds 80 characters')
  - (748, 'Line exceeds 80 characters')
  - (749, 'Line exceeds 80 characters')
  - (753, 'Line exceeds 80 characters')
  - (754, 'Line exceeds 80 characters')
  - (758, 'Line exceeds 80 characters')
  - (759, 'Line exceeds 80 characters')
  - (766, 'Line exceeds 80 characters')
  - (767, 'Line exceeds 80 characters')
  - (771, 'Line exceeds 80 characters')
  - (779, 'Line exceeds 80 characters')
  - (780, 'Line exceeds 80 characters')
  - (784, 'Line exceeds 80 characters')
  - (785, 'Line exceeds 80 characters')
  - (789, 'Line exceeds 80 characters')
  - (790, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
